/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProjectRouteRouteImport } from './routes/_project/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AuthenticatedSubscribeRouteImport } from './routes/_authenticated.subscribe'
import { Route as AuthenticatedOauthConsentRouteImport } from './routes/_authenticated.oauth-consent'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport } from './routes/[.well-known]/openai-apps-challenge'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated.onboarding.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as AppHelpOpenrouterApiKeyRouteImport } from './routes/_app/help/openrouter-api-key'
import { Route as ProjectPProjectIdRouteRouteImport } from './routes/_project/p/$projectId/route'
import { Route as ProjectPProjectIdIndexRouteImport } from './routes/_project/p/$projectId/index'
import { Route as ProjectPProjectIdSettingsRouteImport } from './routes/_project/p/$projectId/settings'
import { Route as ProjectPProjectIdSamRouteImport } from './routes/_project/p/$projectId/sam'
import { Route as ProjectPProjectIdItemsRouteImport } from './routes/_project/p/$projectId/items'
import { Route as ProjectPProjectIdSettingsIndexRouteImport } from './routes/_project/p/$projectId/settings/index'
import { Route as ProjectPProjectIdSettingsContextRouteImport } from './routes/_project/p/$projectId/settings/context'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscribeRoute = AuthenticatedSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOauthConsentRoute =
  AuthenticatedOauthConsentRouteImport.update({
    id: '/oauth-consent',
    path: '/oauth-consent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const Char91DotwellKnownChar93OpenaiAppsChallengeRoute =
  Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport.update({
    id: '/.well-known/openai-apps-challenge',
    path: '/.well-known/openai-apps-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppHelpOpenrouterApiKeyRoute = AppHelpOpenrouterApiKeyRouteImport.update({
  id: '/help/openrouter-api-key',
  path: '/help/openrouter-api-key',
  getParentRoute: () => AppRouteRoute,
} as any)
const ProjectPProjectIdRouteRoute = ProjectPProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectPProjectIdIndexRoute = ProjectPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdSettingsRoute =
  ProjectPProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSamRoute = ProjectPProjectIdSamRouteImport.update({
  id: '/sam',
  path: '/sam',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdItemsRoute = ProjectPProjectIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdSettingsIndexRoute =
  ProjectPProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdSettingsRoute,
  } as any)
const ProjectPProjectIdSettingsContextRoute =
  ProjectPProjectIdSettingsContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => ProjectPProjectIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/support': typeof AppSupportRoute
  '/team': typeof AppTeamRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/health': typeof ApiHealthRoute
  '/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/p/$projectId/items': typeof ProjectPProjectIdItemsRoute
  '/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsRouteWithChildren
  '/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/p/$projectId/settings/': typeof ProjectPProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/projects': typeof AppProjectsRoute
  '/support': typeof AppSupportRoute
  '/team': typeof AppTeamRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/health': typeof ApiHealthRoute
  '/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/settings': typeof AppSettingsIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/p/$projectId/items': typeof ProjectPProjectIdItemsRoute
  '/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/p/$projectId': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_project': typeof ProjectRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/support': typeof AppSupportRoute
  '/_app/team': typeof AppTeamRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/_authenticated/subscribe': typeof AuthenticatedSubscribeRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_project/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/_app/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_project/p/$projectId/items': typeof ProjectPProjectIdItemsRoute
  '/_project/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/_project/p/$projectId/settings': typeof ProjectPProjectIdSettingsRouteWithChildren
  '/_project/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/_project/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/_project/p/$projectId/settings/': typeof ProjectPProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/ai'
    | '/billing'
    | '/projects'
    | '/settings'
    | '/support'
    | '/team'
    | '/sign-in'
    | '/sign-up'
    | '/oauth-consent'
    | '/subscribe'
    | '/accept-invitation/$id'
    | '/api/health'
    | '/p/$projectId'
    | '/help/openrouter-api-key'
    | '/settings/organization'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/settings/'
    | '/onboarding/'
    | '/p/$projectId/items'
    | '/p/$projectId/sam'
    | '/p/$projectId/settings'
    | '/p/$projectId/'
    | '/p/$projectId/settings/context'
    | '/p/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/ai'
    | '/billing'
    | '/projects'
    | '/support'
    | '/team'
    | '/sign-in'
    | '/sign-up'
    | '/oauth-consent'
    | '/subscribe'
    | '/accept-invitation/$id'
    | '/api/health'
    | '/help/openrouter-api-key'
    | '/settings/organization'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/settings'
    | '/onboarding'
    | '/p/$projectId/items'
    | '/p/$projectId/sam'
    | '/p/$projectId'
    | '/p/$projectId/settings/context'
    | '/p/$projectId/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_project'
    | '/_auth'
    | '/_authenticated'
    | '/auth-error'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/_app/ai'
    | '/_app/billing'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/team'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/oauth-consent'
    | '/_authenticated/subscribe'
    | '/accept-invitation/$id'
    | '/api/health'
    | '/_app/'
    | '/_project/p/$projectId'
    | '/_app/help/openrouter-api-key'
    | '/_app/settings/organization'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/_app/settings/'
    | '/_authenticated/onboarding/'
    | '/_project/p/$projectId/items'
    | '/_project/p/$projectId/sam'
    | '/_project/p/$projectId/settings'
    | '/_project/p/$projectId/'
    | '/_project/p/$projectId/settings/context'
    | '/_project/p/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  Char91DotwellKnownChar93OpenaiAppsChallengeRoute: typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscribe': {
      id: '/_authenticated/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AuthenticatedSubscribeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oauth-consent': {
      id: '/_authenticated/oauth-consent'
      path: '/oauth-consent'
      fullPath: '/oauth-consent'
      preLoaderRoute: typeof AuthenticatedOauthConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/.well-known/openai-apps-challenge': {
      id: '/.well-known/openai-apps-challenge'
      path: '/.well-known/openai-apps-challenge'
      fullPath: '/.well-known/openai-apps-challenge'
      preLoaderRoute: typeof Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/help/openrouter-api-key': {
      id: '/_app/help/openrouter-api-key'
      path: '/help/openrouter-api-key'
      fullPath: '/help/openrouter-api-key'
      preLoaderRoute: typeof AppHelpOpenrouterApiKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_project/p/$projectId': {
      id: '/_project/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof ProjectPProjectIdRouteRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/p/$projectId/': {
      id: '/_project/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof ProjectPProjectIdIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/settings': {
      id: '/_project/p/$projectId/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof ProjectPProjectIdSettingsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/sam': {
      id: '/_project/p/$projectId/sam'
      path: '/sam'
      fullPath: '/p/$projectId/sam'
      preLoaderRoute: typeof ProjectPProjectIdSamRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/items': {
      id: '/_project/p/$projectId/items'
      path: '/items'
      fullPath: '/p/$projectId/items'
      preLoaderRoute: typeof ProjectPProjectIdItemsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/settings/': {
      id: '/_project/p/$projectId/settings/'
      path: '/'
      fullPath: '/p/$projectId/settings/'
      preLoaderRoute: typeof ProjectPProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectPProjectIdSettingsRoute
    }
    '/_project/p/$projectId/settings/context': {
      id: '/_project/p/$projectId/settings/context'
      path: '/context'
      fullPath: '/p/$projectId/settings/context'
      preLoaderRoute: typeof ProjectPProjectIdSettingsContextRouteImport
      parentRoute: typeof ProjectPProjectIdSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSupportRoute: typeof AppSupportRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHelpOpenrouterApiKeyRoute: typeof AppHelpOpenrouterApiKeyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBillingRoute: AppBillingRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSupportRoute: AppSupportRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppHelpOpenrouterApiKeyRoute: AppHelpOpenrouterApiKeyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ProjectPProjectIdSettingsRouteChildren {
  ProjectPProjectIdSettingsContextRoute: typeof ProjectPProjectIdSettingsContextRoute
  ProjectPProjectIdSettingsIndexRoute: typeof ProjectPProjectIdSettingsIndexRoute
}

const ProjectPProjectIdSettingsRouteChildren: ProjectPProjectIdSettingsRouteChildren =
  {
    ProjectPProjectIdSettingsContextRoute:
      ProjectPProjectIdSettingsContextRoute,
    ProjectPProjectIdSettingsIndexRoute: ProjectPProjectIdSettingsIndexRoute,
  }

const ProjectPProjectIdSettingsRouteWithChildren =
  ProjectPProjectIdSettingsRoute._addFileChildren(
    ProjectPProjectIdSettingsRouteChildren,
  )

interface ProjectPProjectIdRouteRouteChildren {
  ProjectPProjectIdItemsRoute: typeof ProjectPProjectIdItemsRoute
  ProjectPProjectIdSamRoute: typeof ProjectPProjectIdSamRoute
  ProjectPProjectIdSettingsRoute: typeof ProjectPProjectIdSettingsRouteWithChildren
  ProjectPProjectIdIndexRoute: typeof ProjectPProjectIdIndexRoute
}

const ProjectPProjectIdRouteRouteChildren: ProjectPProjectIdRouteRouteChildren =
  {
    ProjectPProjectIdItemsRoute: ProjectPProjectIdItemsRoute,
    ProjectPProjectIdSamRoute: ProjectPProjectIdSamRoute,
    ProjectPProjectIdSettingsRoute: ProjectPProjectIdSettingsRouteWithChildren,
    ProjectPProjectIdIndexRoute: ProjectPProjectIdIndexRoute,
  }

const ProjectPProjectIdRouteRouteWithChildren =
  ProjectPProjectIdRouteRoute._addFileChildren(
    ProjectPProjectIdRouteRouteChildren,
  )

interface ProjectRouteRouteChildren {
  ProjectPProjectIdRouteRoute: typeof ProjectPProjectIdRouteRouteWithChildren
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectPProjectIdRouteRoute: ProjectPProjectIdRouteRouteWithChildren,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOauthConsentRoute: typeof AuthenticatedOauthConsentRoute
  AuthenticatedSubscribeRoute: typeof AuthenticatedSubscribeRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOauthConsentRoute: AuthenticatedOauthConsentRoute,
  AuthenticatedSubscribeRoute: AuthenticatedSubscribeRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  Char91DotwellKnownChar93OpenaiAppsChallengeRoute:
    Char91DotwellKnownChar93OpenaiAppsChallengeRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
